/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiAlgolia from "strapi-plugin-strapi-algolia/strapi-admin";
import customInputField from "../../src/plugins/custom-input-field/./dist/admin/index.mjs";
import collectionTogglePlugin from "../../src/plugins/collection-toggle-plugin/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    ckeditor: ckeditor,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "strapi-algolia": strapiAlgolia,
    "custom-input-field": customInputField,
    "collection-toggle-plugin": collectionTogglePlugin,
  },
});
